import type { Product } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 299.99,
    originalPrice: 399.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.8,
    reviews: 124,
    description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
    inStock: true,
    colors: ["Black", "White", "Blue"],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.6,
    reviews: 89,
    description: "Advanced fitness tracking with heart rate monitoring and GPS.",
    inStock: true,
    colors: ["Black", "Silver", "Rose Gold"],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    originalPrice: 39.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Clothing",
    rating: 4.4,
    reviews: 67,
    description: "Comfortable organic cotton t-shirt in various colors and sizes.",
    inStock: true,
    colors: ["White", "Black", "Navy", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "4",
    name: "Professional Camera Lens",
    price: 899.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.9,
    reviews: 156,
    description: "Professional grade camera lens for stunning photography.",
    inStock: true,
  },
  {
    id: "5",
    name: "Minimalist Backpack",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    rating: 4.5,
    reviews: 43,
    description: "Sleek and functional backpack perfect for daily use.",
    inStock: true,
    colors: ["Black", "Gray", "Navy"],
  },
  {
    id: "6",
    name: "Wireless Charging Pad",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    rating: 4.3,
    reviews: 78,
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
    inStock: false,
  },
]
